package org.example.demo5.model;

import jakarta.persistence.*;
// Importing necessary classes from the JPA, necessary for using JPA annotation and functionality in class.

@Entity //Marks this class as a JPA entity, JPA treats it as a table in the database.
@Table(name = "Movies") //Name of the database table
public class Movie {       // Movie Class starts
    public Movie() {       //Empty constructor to create instance of Movie, to instantiate objects.
    }

    @Id // primary key for the movie entity
    @GeneratedValue(strategy = GenerationType.AUTO)//Id field will be automatically generated by database using Auto strategy
    @Column(name ="id", nullable = false)
    private Long id;
    private String title;
    private String genre;
    private int releaseyear;
    private String summery;
    private String director;


    /**
     * All the attributes of the Movie class
     * getter & setters to access and update fields of the class.
     * get methods return the current value of the field.
    * set methods to set new value of the field.
     */


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public int getReleaseyear() {
        return releaseyear;
    }

    public void setReleaseyear(int releaseyear) {
        this.releaseyear = releaseyear;
    }

    public String getSummery() {
        return summery;
    }

    public void setSummery(String summery) {
        this.summery = summery;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }
}